# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='somename', max_length=50, null=True)),
                ('second_name', models.CharField(blank=True, default='somesecondname', max_length=50, null=True)),
                ('phone', models.CharField(blank=True, default='somephonenu', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, default='example@email.com', max_length=254, null=True)),
                ('street', models.CharField(blank=True, default='somestreet', max_length=60, null=True)),
                ('house', models.IntegerField(blank=True, default='0', null=True)),
                ('housing', models.IntegerField(blank=True, default='0', null=True)),
                ('building', models.IntegerField(blank=True, default='0', null=True)),
                ('entrance', models.IntegerField(blank=True, default='0', null=True)),
                ('floor', models.IntegerField(blank=True, default='0', null=True)),
                ('room', models.CharField(blank=True, default='someroo,', max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('protein', models.CharField(blank=True, max_length=150)),
                ('carbohydrates', models.CharField(blank=True, max_length=100)),
                ('greens', models.CharField(blank=True, max_length=100)),
                ('other', models.CharField(blank=True, max_length=100)),
                ('pcal', models.IntegerField()),
                ('ccal', models.IntegerField()),
                ('gcal', models.IntegerField()),
                ('ocal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20)),
                ('calories', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('carbohydrates', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to=b'')),
                ('first_description_woman', models.CharField(blank=True, max_length=100)),
                ('first_description_man', models.CharField(blank=True, max_length=100)),
                ('second_description', models.TextField(blank=True, max_length=400)),
                ('third_description', models.TextField(blank=True, max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='ration',
            name='set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.set'),
        ),
    ]
