# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='\u0418\u043c\u044f*')),
                ('email', models.EmailField(max_length=254, verbose_name='Email*')),
                ('topic', models.CharField(blank=True, max_length=100, verbose_name='\u0422\u0435\u043c\u0430')),
                ('letter', models.CharField(max_length=3000, verbose_name='\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435*')),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='\u0418\u043c\u044f*')),
                ('second_name', models.CharField(max_length=50, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f*')),
                ('phone', models.CharField(max_length=20, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d*')),
                ('email', models.EmailField(max_length=254, verbose_name='Email*')),
                ('street', models.CharField(max_length=60, verbose_name='\u0423\u043b\u0438\u0446\u0430*')),
                ('house', models.IntegerField(verbose_name='\u0414\u043e\u043c*')),
                ('housing', models.IntegerField(blank=True, null=True, verbose_name='\u041a\u043e\u0440\u043f\u0443\u0441')),
                ('building', models.IntegerField(blank=True, null=True, verbose_name='\u0421\u0442\u0440\u043e\u0435\u043d\u0438\u0435')),
                ('entrance', models.IntegerField(verbose_name='\u041f\u043e\u0434\u044a\u0435\u0437\u0434*')),
                ('floor', models.IntegerField(verbose_name='\u042d\u0442\u0430\u0436*')),
                ('room', models.IntegerField(verbose_name='\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u0430/\u043e\u0444\u0438\u0441*')),
                ('product_id', models.IntegerField(default=-1)),
                ('duration', models.IntegerField(default=-1)),
                ('price', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='RationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('protein', models.CharField(blank=True, max_length=150)),
                ('carbohydrates', models.CharField(blank=True, max_length=100)),
                ('greens', models.CharField(blank=True, max_length=100)),
                ('other', models.CharField(blank=True, max_length=100)),
                ('pcal', models.IntegerField()),
                ('ccal', models.IntegerField()),
                ('gcal', models.IntegerField()),
                ('ocal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20)),
                ('calories', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('carbohydrates', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to=b'')),
                ('first_description_woman', models.CharField(blank=True, max_length=100)),
                ('first_description_man', models.CharField(blank=True, max_length=100)),
                ('second_description', models.TextField(blank=True, max_length=400)),
                ('third_description', models.TextField(blank=True, max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='rationmodel',
            name='set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ration', to='main_app.SetModel'),
        ),
    ]
