# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='kind',
            field=models.CharField(max_length=10),
        ),
    ]
