# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20160804_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='duration',
            field=models.IntegerField(default=-1),
        ),
    ]
