# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_ordermodel_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='\u0418\u043c\u044f*')),
                ('email', models.EmailField(max_length=254, verbose_name='Email*')),
                ('topic', models.CharField(blank=True, max_length=100, verbose_name='\u0422\u0435\u043c\u0430')),
                ('letter', models.CharField(max_length=3000, verbose_name='\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435*')),
            ],
        ),
    ]
